spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: school
          uri: lb://SCHOOL
          predicates:
            - Path=/schools/**
          filters:
            - JwtAuthorizationFilter
        - id: student
          uri: lb://STUDENT
          predicates:
            - Path=/students/**
          filters:
            - JwtAuthorizationFilter
server:
  port: 8871

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
reactor:
  netty:
    http:
      client: DEBUG