spring:
  application:
    name: student
  data:
    mongodb:
      uri: mongodb://localhost/student
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}